name: just_bottom_sheet
description: Just Bottom Sheet. Bottom sheet with properly working nested scroll and swipe to close gesture.
version: 1.0.1
homepage:
repository: https://github.com/nexron171/JustBottomSheet

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
